# Generated by Django 3.0.3 on 2020-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('using_count', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('answer10', models.IntegerField(default=0)),
                ('answer20', models.IntegerField(default=0)),
                ('answer30', models.IntegerField(default=0)),
                ('answer11', models.IntegerField(default=0)),
                ('answer21', models.IntegerField(default=0)),
                ('answer31', models.IntegerField(default=0)),
                ('answer12', models.IntegerField(default=0)),
                ('answer22', models.IntegerField(default=0)),
                ('answer32', models.IntegerField(default=0)),
                ('answer13', models.IntegerField(default=0)),
                ('answer23', models.IntegerField(default=0)),
                ('answer33', models.IntegerField(default=0)),
                ('answer14', models.IntegerField(default=0)),
                ('answer24', models.IntegerField(default=0)),
                ('answer34', models.IntegerField(default=0)),
            ],
        ),
    ]
