# Generated by Django 3.0.3 on 2020-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('using_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
    ]
